# 3.8
location = ['taipei','japan','korea','singapore','usa']
print(location)
print(sorted(location))
print(location)
print(sorted(location, reverse=True))
print(location)
location.reverse()
print(location)
location.reverse()
print(location)
location.sort()
print(location)
location.sort(reverse=True)
print(location)